stages:
  - push

push_to_github:
  stage: push
  only:
    - main 
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$GITHUB_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git remote | grep -q github || git remote add github git@github.com:shadyemansour/infoVis.git
    - git fsck --full
    - git reflog expire --expire=now --all
    - git gc --prune=now
    - git fetch --all
    - git push github HEAD:main --force